package com.bwf.gui;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.bwf.car.Car;
import com.bwf.gui.service.ProcedureService;
import com.bwf.rental.RentalRecord;

/**
 *
 * @author bwfadmin
 */
public class CarRent extends javax.swing.JFrame {
    private ProcedureService pService ;     //在各层之间控制行为的服务层
    private int index;
    private Car rentedCar;
    public CarRent(ProcedureService pService) {
    	this.pService = pService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rentLicenseNumberField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        rentCarInfoTable = new javax.swing.JTable();
        ensurRentButton = new javax.swing.JButton();
        abandonRentButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rentManField = new javax.swing.JTextField();
        rentManNumberLabel3 = new javax.swing.JLabel();
        rentManNumberField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rentManCellNumberField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rentMoneyField = new javax.swing.JTextField();
        rentDayCountField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        tableModel = new DefaultTableModel(null,
                new String [] {
                    "车牌号", "发动机号", "车名", "颜色", "出厂日期", "里程", "燃油类型", "租车押金", "日租金", "状况","类型"
                });
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("请输入要租借车牌号：");

        rentCarInfoTable.setModel(tableModel);
        rentCarInfoTable.setRowHeight(45);
        rentCarInfoTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(rentCarInfoTable);
        rentCarInfoTable.getAccessibleContext().setAccessibleName("");

        ensurRentButton.setText("确认出租");
        ensurRentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ensurRentButtonMouseClicked(evt);
            }
        });

        abandonRentButton.setText("取消出租");
        abandonRentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abandonRentButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("租车人：");

        rentManNumberLabel3.setText("租车人身份证号码：");

        jLabel4.setText("租车人联系电话：");

        jLabel5.setText("租车缴纳押金：");

        jLabel6.setText("租车天数：");

        searchButton.setText("搜索");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(rentLicenseNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(searchButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(ensurRentButton)
                                .addGap(122, 122, 122)
                                .addComponent(abandonRentButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(185, 185, 185)
                                .addComponent(rentManNumberLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rentManNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rentMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rentManField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rentManCellNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(rentDayCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel6))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rentLicenseNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(searchButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentManField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentManNumberLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentManNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentManCellNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentDayCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abandonRentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ensurRentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }

    private void ensurRentButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	String customer = rentManField.getText();
    	String pid = rentManNumberField.getText();
    	String tel = rentManCellNumberField.getText();
    	double yj =Double.parseDouble( rentMoneyField.getText());
    	int ts =Integer.parseInt( rentDayCountField.getText());
    	if(rentedCar != null){
    		String carCph = rentedCar.getLicenseNumber();
    		String adminName = pService.getAdminList().get(0).getName();
    		RentalRecord record = new RentalRecord(carCph, adminName, customer, pid, tel, yj, ts);
    		ArrayList<RentalRecord> recordList = pService.getRecordList();
    		recordList.add(record);
    		pService.setRecordList(recordList);
    		//将被出租的车的状态设为已出租！
    		rentedCar.setState(Car.STATE_YICHUZU);
    		ArrayList<Car> carList = pService.getCarList();
    		carList.set(index, rentedCar);
    		pService.setCarList(carList);
    		JOptionPane.showMessageDialog(this, "车辆租借成功！");
    	}
    }

    private void abandonRentButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	this.dispose();
    }

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {
    	 String licenseNumber =rentLicenseNumberField.getText();
         ArrayList<Car> carList = pService.getCarList();
         for(Car car : carList){
             if(licenseNumber.trim().equals(car.getLicenseNumber())){
             	index = carList.indexOf(car);
             	rentedCar = car;
             }
         }
         if(rentedCar != null){
             if(rentedCar.getState().equals(Car.STATE_BAOFEI)){
                 JOptionPane.showMessageDialog(this, "该车已报废。。。");
             }else if(rentedCar.getState().equals(Car.STATE_YICHUZU)){
             	JOptionPane.showMessageDialog(this, "该车已经出租，暂时不能出租！");
             }else{
                     //将信息显示到表格中
             	Object[] info = rentedCar.returnInfo();
             	tableModel.addRow(info);
             }
         }
         else
         	JOptionPane.showMessageDialog(this, "未找到该车牌号！库存无此车");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abandonRentButton;
    private javax.swing.JButton ensurRentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rentCarInfoTable;
    private javax.swing.JTextField rentDayCountField;
    private javax.swing.JTextField rentLicenseNumberField;
    private javax.swing.JTextField rentManCellNumberField;
    private javax.swing.JTextField rentManField;
    private javax.swing.JTextField rentManNumberField;
    private javax.swing.JLabel rentManNumberLabel3;
    private javax.swing.JTextField rentMoneyField;
    private javax.swing.JButton searchButton;
    private DefaultTableModel tableModel ;
    // End of variables declaration//GEN-END:variables
}
