/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bwf.gui;

import com.bwf.admin.Admin;
import com.bwf.gui.service.ProcedureService;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bwfadmin
 */
public class ModifyPsw extends javax.swing.JFrame {
    private ProcedureService pService ;     //在各层之间控制行为的服务层
    
    public ModifyPsw(ProcedureService pService) {
        this.pService = pService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ensureModifyPswButton = new javax.swing.JButton();
        clearModifyPswButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        modifyOldPswField = new javax.swing.JTextField();
        modifyNewPswField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("汽车管理系统");

        jLabel1.setText("旧密码：");

        ensureModifyPswButton.setText("确定修改");
        ensureModifyPswButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ensureModifyPswButtonMouseClicked(evt);
            }
        });

        clearModifyPswButton.setText("清空");
        clearModifyPswButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearModifyPswButtonMouseClicked(evt);
            }
        });

        jLabel3.setText("新密码：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifyNewPswField, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modifyOldPswField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(ensureModifyPswButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(clearModifyPswButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(modifyOldPswField)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(modifyNewPswField))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ensureModifyPswButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearModifyPswButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ensureModifyPswButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ensureModifyPswButtonMouseClicked
        String oldPsw = modifyOldPswField.getText();
        String newPsw = modifyNewPswField.getText();
        ArrayList<Admin> adminList = pService.getAdminList();
        Admin loginAdmin = adminList.get(0);
        if(oldPsw.trim().equals(loginAdmin.getLoginPsw())){
            adminList.add(new Admin(loginAdmin.getLoginId(),newPsw,loginAdmin.getName()));
            pService.setAdminList(adminList);
            JOptionPane.showMessageDialog(this, "密码修改成功！");
        }else{
             JOptionPane.showMessageDialog(this, "旧密码不正确，请重新输入！");
        }
    }//GEN-LAST:event_ensureModifyPswButtonMouseClicked

    private void clearModifyPswButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearModifyPswButtonMouseClicked
        modifyOldPswField.setText("");
        modifyNewPswField.setText("");
    }//GEN-LAST:event_clearModifyPswButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearModifyPswButton;
    private javax.swing.JButton ensureModifyPswButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField modifyNewPswField;
    private javax.swing.JTextField modifyOldPswField;
    // End of variables declaration//GEN-END:variables
}
